# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from PyQt5.QtWidgets import QWidget
from PyQt5.QtCore import Qt, QPoint
from PyQt5.QtGui import QPixmap, QPainter, QPen

class DrawingWidget(QWidget):
    def __init__(self, parent = None):
        super().__init__(parent)
        self.pix = QPixmap(460, 190)

        self.pix.fill(Qt.black)
        self.penColor = Qt.white

        self.lastPoint = QPoint()
        self.endPoint = QPoint()

    def paintEvent(self, event):
        painter = QPainter(self)
        painter.drawPixmap(0, 0, self.pix)

    def mousePressEvent(self, event):
        if event.button() == Qt.LeftButton:
            self.lastPoint = event.pos()

    def mouseMoveEvent(self, event):
        if event.buttons() & Qt.LeftButton:
            self.endPoint = event.pos()
            self.drawOnLabel()

    def mouseReleaseEvent(self, event):
        if event.button() == Qt.LeftButton:
            self.endPoint = event.pos()
            self.drawOnLabel()

    def drawOnLabel(self):
        pp = QPainter(self.pix)
        pp.setPen(QPen(self.penColor, 15, Qt.SolidLine))

        pp.drawLine(self.lastPoint, self.endPoint)

        self.lastPoint = self.endPoint
        self.update()

    def clearDrawing(self):
        self.pix.fill(Qt.black)
        self.update()

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1111, 651)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame1 = QtWidgets.QFrame(self.centralwidget)
        self.frame1.setGeometry(QtCore.QRect(160, 60, 211, 171))
        self.frame1.setFrameShape(QtWidgets.QFrame.Box)
        self.frame1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame1.setLineWidth(1)
        self.frame1.setObjectName("frame1")
        self.Button1_1 = QtWidgets.QPushButton(self.frame1)
        self.Button1_1.setGeometry(QtCore.QRect(20, 50, 151, 31))
        self.Button1_1.setObjectName("Button1_1")
        self.label1 = QtWidgets.QLabel(self.frame1)
        self.label1.setGeometry(QtCore.QRect(10, 10, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label1.setFont(font)
        self.label1.setObjectName("label1")
        self.Button1_2 = QtWidgets.QPushButton(self.frame1)
        self.Button1_2.setGeometry(QtCore.QRect(20, 100, 151, 31))
        self.Button1_2.setObjectName("Button1_2")
        self.count_coin = QtWidgets.QLabel(self.frame1)
        self.count_coin.setGeometry(QtCore.QRect(20, 140, 181, 16))
        self.count_coin.setObjectName("count_coin")
        self.loadButton1 = QtWidgets.QPushButton(self.centralwidget)
        self.loadButton1.setGeometry(QtCore.QRect(30, 280, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.loadButton1.setFont(font)
        self.loadButton1.setObjectName("loadButton1")
        self.loadLabel1 = QtWidgets.QLabel(self.centralwidget)
        self.loadLabel1.setGeometry(QtCore.QRect(40, 330, 101, 16))
        self.loadLabel1.setObjectName("loadLabel1")
        self.frame2 = QtWidgets.QFrame(self.centralwidget)
        self.frame2.setGeometry(QtCore.QRect(160, 250, 211, 101))
        self.frame2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame2.setLineWidth(1)
        self.frame2.setObjectName("frame2")
        self.Button1_3 = QtWidgets.QPushButton(self.frame2)
        self.Button1_3.setGeometry(QtCore.QRect(30, 60, 151, 31))
        self.Button1_3.setObjectName("Button1_3")
        self.label2 = QtWidgets.QLabel(self.frame2)
        self.label2.setGeometry(QtCore.QRect(10, 10, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label2.setFont(font)
        self.label2.setObjectName("label2")
        self.frame3 = QtWidgets.QFrame(self.centralwidget)
        self.frame3.setGeometry(QtCore.QRect(160, 370, 211, 131))
        self.frame3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame3.setLineWidth(1)
        self.frame3.setObjectName("frame3")
        self.Button1_4 = QtWidgets.QPushButton(self.frame3)
        self.Button1_4.setGeometry(QtCore.QRect(20, 50, 151, 31))
        self.Button1_4.setObjectName("Button1_4")
        self.label3 = QtWidgets.QLabel(self.frame3)
        self.label3.setGeometry(QtCore.QRect(10, 10, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label3.setFont(font)
        self.label3.setObjectName("label3")
        self.Button1_5 = QtWidgets.QPushButton(self.frame3)
        self.Button1_5.setGeometry(QtCore.QRect(20, 90, 151, 31))
        self.Button1_5.setObjectName("Button1_5")
        self.frame4 = QtWidgets.QFrame(self.centralwidget)
        self.frame4.setGeometry(QtCore.QRect(390, 20, 701, 251))
        self.frame4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame4.setLineWidth(1)
        self.frame4.setObjectName("frame4")
        self.label4 = QtWidgets.QLabel(self.frame4)
        self.label4.setGeometry(QtCore.QRect(20, 10, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label4.setFont(font)
        self.label4.setObjectName("label4")
        self.Button1_6 = QtWidgets.QPushButton(self.frame4)
        self.Button1_6.setGeometry(QtCore.QRect(30, 60, 151, 31))
        self.Button1_6.setObjectName("Button1_6")
        self.Button1_7 = QtWidgets.QPushButton(self.frame4)
        self.Button1_7.setGeometry(QtCore.QRect(30, 100, 151, 31))
        self.Button1_7.setObjectName("Button1_7")
        self.Button1_8 = QtWidgets.QPushButton(self.frame4)
        self.Button1_8.setGeometry(QtCore.QRect(30, 140, 151, 31))
        self.Button1_8.setObjectName("Button1_8")
        self.Button1_9 = QtWidgets.QPushButton(self.frame4)
        self.Button1_9.setGeometry(QtCore.QRect(30, 190, 151, 31))
        self.Button1_9.setObjectName("Button1_9")
        self.frame5 = QtWidgets.QFrame(self.centralwidget)
        self.frame5.setGeometry(QtCore.QRect(390, 280, 701, 321))
        self.frame5.setFrameShape(QtWidgets.QFrame.Box)
        self.frame5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame5.setLineWidth(1)
        self.frame5.setObjectName("frame5")
        self.Button1_10 = QtWidgets.QPushButton(self.frame5)
        self.Button1_10.setGeometry(QtCore.QRect(20, 50, 151, 31))
        self.Button1_10.setObjectName("Button1_10")
        self.label5 = QtWidgets.QLabel(self.frame5)
        self.label5.setGeometry(QtCore.QRect(20, 10, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label5.setFont(font)
        self.label5.setObjectName("label5")
        self.label5_1 = QtWidgets.QLabel(self.frame5)
        self.label5_1.setGeometry(QtCore.QRect(570, 200, 151, 16))
        self.label5_1.setObjectName("label5_1")
        self.Button1_11 = QtWidgets.QPushButton(self.frame5)
        self.Button1_11.setGeometry(QtCore.QRect(20, 90, 171, 41))
        self.Button1_11.setObjectName("Button1_11")
        self.Button1_12 = QtWidgets.QPushButton(self.frame5)
        self.Button1_12.setEnabled(True)
        self.Button1_12.setGeometry(QtCore.QRect(20, 140, 171, 41))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.Button1_12.setFont(font)
        self.Button1_12.setMouseTracking(False)
        self.Button1_12.setAcceptDrops(False)
        self.Button1_12.setAutoRepeat(False)
        self.Button1_12.setDefault(False)
        self.Button1_12.setFlat(False)
        self.Button1_12.setObjectName("Button1_12")
        self.Button1_13 = QtWidgets.QPushButton(self.frame5)
        self.Button1_13.setGeometry(QtCore.QRect(20, 200, 151, 31))
        self.Button1_13.setObjectName("Button1_13")
        self.Button1_14 = QtWidgets.QPushButton(self.frame5)
        self.Button1_14.setGeometry(QtCore.QRect(20, 250, 151, 31))
        self.Button1_14.setObjectName("Button1_14")
        self.image_label = QtWidgets.QLabel(self.frame5)
        self.image_label.setGeometry(QtCore.QRect(250, 10, 300, 300))
        self.image_label.setFrameShape(QtWidgets.QFrame.Box)
        self.image_label.setText("")
        self.image_label.setObjectName("image_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1111, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.drawingWidget = DrawingWidget(self.frame4)
        self.drawingWidget.setGeometry(QtCore.QRect(200, 50, 460, 190))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Button1_1.setText(_translate("MainWindow", "1.1 Draw Contour"))
        self.label1.setText(_translate("MainWindow", "1. Hough Circle Transform"))
        self.Button1_2.setText(_translate("MainWindow", "1.2 Count Coins"))
        self.count_coin.setText(_translate("MainWindow", "There are _ coins in the image"))
        self.loadButton1.setText(_translate("MainWindow", "Load Image 1"))
        self.loadLabel1.setText(_translate("MainWindow", "No image loaded"))
        self.Button1_3.setText(_translate("MainWindow", "2. Histogram Equlization"))
        self.label2.setText(_translate("MainWindow", "2. Histogram Equlization"))
        self.Button1_4.setText(_translate("MainWindow", "3.1 Closing"))
        self.label3.setText(_translate("MainWindow", "3. Morphology Operation"))
        self.Button1_5.setText(_translate("MainWindow", "3.2 Opening"))
        self.label4.setText(_translate("MainWindow", "4. MNIST Classifier Using VGG19"))
        self.Button1_6.setText(_translate("MainWindow", "1. Show Model Structure"))
        self.Button1_7.setText(_translate("MainWindow", "2. Show Acc and Loss"))
        self.Button1_8.setText(_translate("MainWindow", "3. Predict"))
        self.Button1_9.setText(_translate("MainWindow", "4. Reset"))
        self.Button1_10.setText(_translate("MainWindow", "Load Image"))
        self.label5.setText(_translate("MainWindow", "5. ResNet50"))
        self.Button1_11.setText(_translate("MainWindow", "5.1 Show Images"))
        self.Button1_12.setText(_translate("MainWindow", "5.2 Show Model Structure"))
        self.Button1_13.setText(_translate("MainWindow", "5.3 Show Comparasion"))
        self.Button1_14.setText(_translate("MainWindow", "5.4 Inference"))
        self.label5_1.setText(_translate("MainWindow", "Predict ="))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
